### ISSUE TITLE
MCP server: persona-scoped tool exposure for running tasks

### ISSUE THREAD

**Issue by nick-pape** [nick-pape/grackle#424]
## Summary

Running Grackle tasks should receive a **persona-scoped subset** of the MCP tool surface. Instead of the current hardcoded `SCOPED_TOOLS` set in `packages/mcp/src/tool-scoping.ts`, personas should define which MCP tools their tasks can access. When a persona has no explicit tool list, the current default set is preserved for backward compatibility.

## Current State

Today, scoped-token callers (running tasks) receive a **static set of 18 tools** defined in `SCOPED_TOOLS` (`packages/mcp/src/tool-scoping.ts`):

```
finding_post, finding_list,
task_create, task_list, task_show, task_start, task_complete,
session_send_input,
persona_list, persona_show,
ipc_spawn, ipc_write, ipc_close, ipc_terminate, ipc_list_fds,
knowledge_search, knowledge_get_node,
workpad_write, workpad_read
```

This set is the same for **all** scoped-token callers regardless of persona. There is no way to restrict or expand tools per persona.

## Full Tool Registry (53 tools)

The MCP server (`packages/mcp/src/tools/`) registers these tools, grouped by category:

| Group | Tools |
|-------|-------|
| **config** | `config_get_default_persona`, `config_set_default_persona` |
| **credential** | `credential_provider_list`, `credential_provider_set` |
| **env** | `env_list`, `env_add`, `env_provision`, `env_stop`, `env_destroy`, `env_remove`, `env_wake` |
| **finding** | `finding_list`, `finding_post` |
| **ipc** | `ipc_spawn`, `ipc_write`, `ipc_close`, `ipc_list_fds`, `ipc_terminate` |
| **knowledge** | `knowledge_search`, `knowledge_get_node`, `knowledge_create_node` |
| **logs** | `logs_get` |
| **persona** | `persona_list`, `persona_create`, `persona_show`, `persona_edit`, `persona_delete` |
| **session** | `session_spawn`, `session_resume`, `session_status`, `session_kill`, `session_attach`, `session_send_input` |
| **task** | `task_list`, `task_create`, `task_show`, `task_update`, `task_start`, `task_delete`, `task_complete`, `task_resume` |
| **token** | `token_list`, `token_set`, `token_delete` |
| **usage** | `usage_get` |
| **version** | `get_version_status` |
| **workpad** | `workpad_write`, `workpad_read` |
| **workspace** | `workspace_list`, `workspace_create`, `workspace_get`, `workspace_update`, `workspace_archive` |

---

### Overview

This issue adds persona-scoped MCP tool filtering. When a task agent connects to the Grackle MCP server, the server uses the scoped token (which already carries `personaId` via #423) to look up the persona and restrict `tools/list` and `tools/call` to only the tools that persona permits. Full-access clients (API key, OAuth) continue to see all tools.

### Functional Requirements

**FR-1: Persona-level `allowed_mcp_tools` field.**
Add a `repeated string allowed_mcp_tools = 14;` field to the `Persona` proto message. This field lists the exact MCP tool names (matching the tool registry names above, e.g., `finding_post`, `task_create`, `knowledge_search`) that agents running with this persona may call. When empty, the current default set (`SCOPED_TOOLS`) is applied for backward compatibility. Also add the field to `CreatePersonaRequest` and `UpdatePersonaRequest`.

This is distinct from:
- `ToolConfig.allowed_tools` / `ToolConfig.disallowed_tools` -- which control the agent SDK built-in tool allowlist/blocklist (e.g., `Bash`, `Write`, `mcp__playwright__*`)
- `McpServerConfig.tools` -- which controls per-server tool lists for *non-Grackle* MCP servers configured on the persona

The new `allowed_mcp_tools` specifically controls the Grackle MCP server tool surface for that persona.

**FR-2: Dynamic `tools/list` filtering.**
When a task agent calls `tools/list` on the Grackle MCP server, the server must:
  1. Extract the `personaId` from the scoped token claims (already available in `AuthContext`).
  2. Call `grpcClient.getPersona({ id: personaId })` to fetch the persona `allowed_mcp_tools`.
  3. If `allowed_mcp_tools` is non-empty, return only the tools whose names appear in that list.
  4. If `allowed_mcp_tools` is empty, fall back to the current `SCOPED_TOOLS` set (18 tools).
  5. For full-access clients (API key, OAuth), return the complete tool surface without filtering.
  6. Cache the resolved tool set per MCP session (persona ID is immutable in token claims).

**FR-3: Default tool set preserved.**
When a persona has an empty `allowed_mcp_tools` list (including all existing personas), the MCP server applies the current `SCOPED_TOOLS` default:

```
finding_post, finding_list,
task_create, task_list, task_show, task_start, task_complete,
session_send_input,
persona_list, persona_show,
ipc_spawn, ipc_write, ipc_close, ipc_terminate, ipc_list_fds,
knowledge_search, knowledge_get_node,
workpad_write, workpad_read
```

This ensures **no behavioral regression** for existing personas.

**FR-4: Predefined tool set constants.**
Define named constants in `@grackle-ai/common` for common tool sets:

| Constant | Tools |
|----------|-------|
| `DEFAULT_SCOPED_TOOLS` | The current 18-tool `SCOPED_TOOLS` set (default for empty `allowed_mcp_tools`) |
| `WORKER_TOOLS` | `finding_post`, `finding_list`, `task_create`, `workpad_write`, `workpad_read` |
| `ORCHESTRATOR_TOOLS` | All `DEFAULT_SCOPED_TOOLS` + `task_update`, `task_delete`, `task_resume`, `session_spawn`, `session_kill`, `session_status`, `persona_create`, `knowledge_create_node` |
| `ADMIN_TOOLS` | All 53 tools (sentinel: full access, no filtering) |

These constants are used by the CLI `--mcp-tools-preset` flag, the web UI preset buttons, and unit tests.

**FR-5: Tool call rejection for non-permitted tools.**
When a task agent calls a tool not in its persona allowed set, the MCP server must return an MCP error result:
- `isError: true`
- Message: `Tool "<tool_name>" is not available for persona "<persona_name>". Available tools: <comma-separated list>`

This replaces the current generic `"Unknown tool: <name>"` message for scoped callers hitting tools outside their set.

**FR-6: Server-side validation of `allowed_mcp_tools`.**
When creating or updating a persona with `allowed_mcp_tools`, the server must validate every tool name against the MCP tool registry. Reject with `INVALID_ARGUMENT` if any name is not a known tool. This prevents typos and stale references.

The tool registry names are the source of truth. Export the full list of valid tool names from `@grackle-ai/mcp` (or `@grackle-ai/common` if a static list is preferred) for validation.

**FR-7: Persona schema changes -- database and proto.**
- **Proto**: Add `repeated string allowed_mcp_tools = 14;` to `Persona`, field 11 to `CreatePersonaRequest`, field 12 to `UpdatePersonaRequest`.
- **SQLite schema**: Add `allowed_mcp_tools` column (`TEXT NOT NULL DEFAULT '[]'`) to the `personas` table via ALTER TABLE migration in `db.ts`.
- **persona-store.ts**: Update `createPersona()` and `updatePersona()` to accept and persist the new field.
- **grpc-service.ts**: Update `personaRowToProto()`, `createPersona()`, and `updatePersona()` handlers to map the new field. Add validation (FR-6) in the create/update handlers.

**FR-8: CLI support for `allowed_mcp_tools`.**
- `grackle persona create` gains `--mcp-tools <tools...>` (comma-separated list of MCP tool names).
- `grackle persona edit` gains `--mcp-tools <tools...>` to replace the tool set and `--mcp-tools-preset <worker|orchestrator|admin|default>` for convenience.
- `grackle persona show` displays the allowed MCP tools list.
- CLI validates tool names client-side where feasible (the predefined constants are available from `@grackle-ai/common`). Server-side validation (FR-6) is the authoritative check.

**FR-9: Web UI multiselect for MCP tools.**
Add a multiselect component to the persona create/edit forms in the web UI (`packages/web`):
- Display the full tool registry as a categorized multiselect (grouped by tool group: env, session, task, finding, etc.).
- Preset buttons for Worker / Orchestrator / Admin / Default that populate the selection.
- Show the selected tools in persona show / detail views.
- Empty selection means "use default" (the current `SCOPED_TOOLS` set).

**FR-10: Tool filtering middleware architecture.**
Refactor `tool-scoping.ts` to support persona-aware filtering:
1. Make `listToolsForAuth()` and `resolveToolForAuth()` async (or accept a pre-resolved tool set).
2. At MCP session creation in `createMcpServerInstance()`, resolve the persona allowed tools via gRPC and cache the result for the session lifetime.
3. Pass the resolved tool set into the scoping functions.
4. For full-access tokens, skip filtering (no change from current behavior).

### Non-Functional Requirements

**NFR-1: Backward compatibility.**
Existing personas (with no `allowed_mcp_tools` field) continue to work with the current 18-tool `SCOPED_TOOLS` default. No data migration required -- empty/missing JSON array maps to the default.

**NFR-2: Performance.**
Tool filtering on `tools/list` must add negligible latency. The persona lookup is cached per MCP session. A `Set<string>` membership check is sufficient.

**NFR-3: Observability.**
- Log (pino) when a tool call is rejected due to persona restrictions: persona ID, tool name, task ID.
- Log at session start which tools were exposed, at `info` level.

**NFR-4: Security.**
- Tool filtering is enforced server-side. The agent cannot bypass it.
- `allowed_mcp_tools` is an allowlist -- only listed tools are accessible (deny-by-default for non-empty lists).
- Full-access clients (API key, OAuth) are exempt. Root task (`systemId`) is exempt.

**NFR-5: Testability.**
The tool filtering logic must be a pure function: takes a list of all tool definitions + a set of allowed names, returns filtered list. Enables unit testing without MCP infrastructure.

### Integration Points

**With `packages/mcp/src/tool-scoping.ts`:** Replace the hardcoded `SCOPED_TOOLS` filtering with persona-aware logic. The existing `hasFullAccess()` check is preserved.

**With `packages/mcp/src/mcp-server.ts`:** `createMcpServerInstance()` gains a persona lookup step for scoped auth contexts. The resolved tool set is passed to the scoping layer.

**With `packages/mcp/src/tool-registry.ts`:** Export the list of all registered tool names for validation (FR-6).

**With `packages/auth/src/auth-context.ts`:** Already carries `personaId` on scoped auth -- no changes needed.

**With `packages/common/src/proto/grackle/grackle.proto`:** Proto schema changes (FR-7).

**With `packages/database/src/schema.ts` and `persona-store.ts`:** DB schema and store changes (FR-7).

**With `packages/core/src/grpc-service.ts`:** Persona CRUD handler updates + validation (FR-6, FR-7).

**With `packages/cli/src/commands/persona.ts`:** CLI flag additions (FR-8).

**With `packages/web/`:** Multiselect UI for persona tool configuration (FR-9).

### Acceptance Criteria -- Unit Tests

**UT-1: Tool filtering pure function.**
Given a full tool list of 53 tools and an allowed set of `["finding_post", "finding_list", "task_create"]`, the filter function returns exactly those 3 tools.

**UT-2: Empty allowed set returns default scoped tools.**
Given an empty `allowed_mcp_tools` array, the filter function returns the 18 default `SCOPED_TOOLS`.

**UT-3: Unknown tool names in allowed list are rejected at write time.**
Given `allowed_mcp_tools = ["finding_post", "nonexistent_tool"]` in a `CreatePersonaRequest`, the server returns `INVALID_ARGUMENT`.

**UT-4: ADMIN_TOOLS bypasses filtering.**
When `allowed_mcp_tools` equals `ADMIN_TOOLS` (all 53 tools), the filter returns the complete tool list.

**UT-5: Tool call rejection.**
When a tool call for `env_add` is dispatched but the persona allowed set is `WORKER_TOOLS`, the middleware returns an MCP error with the expected message format including persona name.

**UT-6: Full-access tokens skip filtering.**
When the auth type is `api-key` (no `personaId`), all tool calls pass without filtering.

**UT-7: Persona proto serialization round-trip.**
A `Persona` message with `allowed_mcp_tools = ["finding_post", "task_create"]` survives proto serialization and deserialization intact.

**UT-8: Persona store persistence.**
Creating a persona with `allowedMcpTools = '["finding_post"]'` and reading it back returns the same value.

**UT-9: Predefined tool set constants.**
`DEFAULT_SCOPED_TOOLS`, `WORKER_TOOLS`, `ORCHESTRATOR_TOOLS`, and `ADMIN_TOOLS` are exported from `@grackle-ai/common` and contain the expected tool names.

**UT-10: Validation rejects invalid tool names.**
`CreatePersonaRequest` with `allowed_mcp_tools = ["finding_post", "fake_tool"]` returns `INVALID_ARGUMENT` with the invalid name in the error message.

### Acceptance Criteria -- Integration Tests

**IT-1: End-to-end tool filtering via MCP protocol.**
Create a persona with `allowed_mcp_tools = ["finding_post"]`. Start a task with that persona. Connect to the MCP server with the task scoped token. Call `tools/list` and verify only `finding_post` is returned.

**IT-2: Tool call rejection via MCP protocol.**
Using the same scoped token as IT-1, call `tools/call` for `env_list`. Verify the response is an MCP error with the expected message.

**IT-3: Full-access client sees all tools.**
Connect to the MCP server with an API key. Call `tools/list` and verify all 53 tools are returned.

**IT-4: Default tool set for legacy persona.**
Create a persona without specifying `allowed_mcp_tools`. Start a task with that persona. Verify `tools/list` returns exactly the 18 default scoped tools.

**IT-5: Persona update reflects in next session.**
Create a persona with worker tools. Start a task (sees 5 tools). Update the persona to add `task_list`. Start a new task with the same persona. Verify the new task sees 6 tools. (The first task tools do not change mid-session.)

### Acceptance Criteria -- Manual Testing

**MT-1: CLI persona creation with MCP tools.**
Run `grackle persona create "Test Worker" --prompt "You are a worker." --mcp-tools finding_post,finding_list,task_create`. Run `grackle persona show <id>` and verify the MCP tools are displayed.

**MT-2: CLI preset tool sets.**
Run `grackle persona edit <id> --mcp-tools-preset orchestrator`. Verify the persona allowed MCP tools match `ORCHESTRATOR_TOOLS`.

**MT-3: Web UI multiselect.**
Open persona create/edit in the web UI. Verify the MCP tools multiselect displays all 53 tools grouped by category. Select a preset, verify the selection updates. Save and verify the persona detail view shows the selected tools.

**MT-4: Validation rejects bad tool names.**
Run `grackle persona create "Bad" --prompt "test" --mcp-tools finding_post,not_a_real_tool`. Verify the server rejects with an error naming the invalid tool.

### Out of Scope

- **Per-tool parameter scoping** (e.g., restricting `task_list` to only the task own workspace) -- finer-grained authorization for a follow-up.
- **Wildcard/glob patterns** (e.g., `task_*`) in `allowed_mcp_tools` -- explicit enumeration only in v1. The multiselect UI and presets make this ergonomic enough.
- **Dynamic tool injection** (adding tools at runtime not in the static registry) -- not in scope.
- **MCP stub migration** -- already completed. The MCP broker injection via `resolveMcpServers()` replaces the old stub.
- **Event-stream interception removal** -- already completed. No interception code exists in `claude-code.ts`.

### Open Questions

**OQ-1: Tool set immutability during a session.**
If a persona `allowed_mcp_tools` is updated while a task is running, should the running session see the new tools? **Decision: No.** The tool set is resolved at session start and cached. A new task must be started to pick up changes.

**Comment by nick-pape** [comment]
## Requirements Specification

### Overview

This issue defines persona-scoped MCP tool filtering for running tasks. When a task agent connects to the Grackle MCP server (established in #421), the server must use the task's scoped token (from #423) to identify its persona and dynamically restrict the `tools/list` response to only the tools that persona is permitted to use. Tool calls to non-permitted tools must be rejected with a clear MCP error. This replaces the current hardcoded 3-tool MCP stub in `packages/powerline/mcp-grackle/` with a unified, persona-aware tool surface drawn from the full ~35 tools defined in #422.

### Functional Requirements

**FR-1: Persona-level `allowed_mcp_tools` field.**
Add a `repeated string allowed_mcp_tools` field to the `Persona` proto message. This field lists the exact MCP tool names (using the `group_action` naming convention from #422, e.g., `finding_post`, `task_create`, `finding_query`) that agents running with this persona may call. When empty, a default tool set is applied based on the persona's archetype (see FR-3). This is distinct from the existing `ToolConfig.allowed_tools` / `ToolConfig.disallowed_tools`, which control the agent SDK's built-in tool allowlist/blocklist (e.g., `Bash`, `Write`, `mcp__playwright__*`) and are passed directly to the Claude Agent SDK. The new `allowed_mcp_tools` controls access at the Grackle MCP server layer only.

**FR-2: Dynamic `tools/list` filtering.**
When a task agent calls `tools/list` on the Grackle MCP server, the server must:
  1. Extract the persona ID from the scoped token's claims (provided by #423).
  2. Look up the persona's `allowed_mcp_tools` list.
  3. Return only the tools whose names appear in that list (or the default set if the list is empty).
  4. For full-access clients (API key auth, not task-scoped), return the complete tool surface without filtering.

**FR-3: Default tool sets for personas without explicit `allowed_mcp_tools`.**
When a persona has an empty `allowed_mcp_tools` list, the MCP server applies a default "worker" tool set:
  - `finding_post` -- share discoveries with other agents
  - `finding_query` -- query findings from other agents
  - `task_create_subtask` -- delegate work by creating child tasks (maps to `create_subtask` in the current stub)

This matches the current 3-tool stub behavior and ensures backward compatibility.

**FR-4: Predefined tool set constants.**
Define named constants for common tool sets that can be referenced when creating personas:

| Constant Name | Tools |
|--------------|-------|
| `WORKER_TOOLS` | `finding_post`, `finding_query`, `task_create_subtask` |
| `ORCHESTRATOR_TOOLS` | All worker tools + `task_list`, `task_create`, `task_show`, `task_start`, `task_update`, `task_delete`, `task_approve`, `task_reject`, `project_list`, `project_create`, `finding_list` |
| `ADMIN_TOOLS` | All tools (no filtering applied) |

These constants live in `@grackle-ai/common` so both the server and CLI can reference them. The actual tool names must match the names defined in #422.

**FR-5: Tool call rejection for non-permitted tools.**
When a task agent calls a tool that is not in its persona's allowed set, the MCP server must return an MCP error with:
  - Error code: `InvalidRequest` (or the closest MCP standard error)
  - A human-readable message: `Tool "<tool_name>" is not available for persona "<persona_name>". Available tools: <comma-separated list>`

This ensures the agent can understand what went wrong and adjust.

**FR-6: Persona schema changes -- database and proto.**
- **Proto**: Add `repeated string allowed_mcp_tools = 12;` to the `Persona` message in `grackle.proto`. Also add it to `CreatePersonaRequest` and `UpdatePersonaRequest`.
- **SQLite schema**: Add an `allowed_mcp_tools` column (TEXT, default `"[]"`) to the `personas` table in `schema.ts`. Store as a JSON array of strings.
- **persona-store.ts**: Update `createPersona()` and `updatePersona()` to accept and persist the new field.
- **grpc-service.ts**: Update `personaRowToProto()`, `createPersona()`, and `updatePersona()` handlers to map the new field.

**FR-7: CLI support for `allowed_mcp_tools`.**
- `grackle persona create` gains `--mcp-tools <tools...>` (comma-separated list of MCP tool names).
- `grackle persona edit` gains `--mcp-tools <tools...>` to replace the tool set and `--mcp-tools-preset <worker|orchestrator|admin>` for convenience.
- `grackle persona show` displays the allowed MCP tools list.

**FR-8: Tool filtering middleware architecture.**
Tool filtering must be implemented as middleware in the MCP server's request pipeline, not embedded in individual tool handlers. The middleware:
  1. Runs after authentication (which resolves the token claims).
  2. On `tools/list`: filters the tool definitions array to only include permitted tools.
  3. On `tools/call`: checks if the requested tool is in the permitted set before dispatching.
  4. Is a no-op for full-access tokens (API key auth).

**FR-9: Migration from MCP stub to real MCP server.**
When starting a task, the server must configure the agent to connect to the Grackle MCP server instead of the current stub:
  1. In `runtime-utils.ts`, the auto-injection of `GRACKLE_MCP_SCRIPT` is replaced with an MCP server entry pointing to the Grackle MCP server's Streamable HTTP endpoint (e.g., `http://host.docker.internal:<mcp-port>/mcp` or the appropriate host for the environment's network topology).
  2. The `GRACKLE_MCP_CONFIG` env var (or the `mcpServersJson` field on the PowerLine `SpawnRequest`) must include the scoped token for authentication.
  3. The existing `disallowedTools` pattern in `resolveMcpServers()` continues to work for non-Grackle MCP servers (e.g., Playwright).

**FR-10: Event-stream interception compatibility.**
The current event-stream interception pattern in `claude-code.ts` (lines 50-63) intercepts `mcp__grackle__post_finding` and `mcp__grackle__create_subtask` tool calls to emit `finding` and `subtask_create` events. After migration:
  - If the MCP server handles these tools server-side (calling the gRPC `PostFinding` / `CreateTask` RPCs directly), the interception in `claude-code.ts` is no longer needed for those tools and should be removed to avoid double-processing.
  - If the interception pattern is retained for latency or reliability reasons, the MCP server tools must remain stubs (returning confirmations) and the interception code must be preserved.
  - **Decision**: The recommended approach is to let the MCP server handle the gRPC calls directly (thin client pattern from #420), and remove the event-stream interception for `post_finding` and `create_subtask`. The `finding` and `subtask_create` events should instead be emitted by the server's gRPC handlers (via WebSocket broadcast), which already happens for `PostFinding` and `CreateTask`.

### Non-Functional Requirements

**NFR-1: Backward compatibility.**
Existing personas created before this change (with no `allowed_mcp_tools` field) must continue to work. They receive the default worker tool set (FR-3). No data migration is required -- an empty/missing JSON array maps to the default.

**NFR-2: Performance.**
Tool filtering on `tools/list` must add negligible latency. The persona lookup should be cached for the duration of the MCP session (the persona ID is immutable in the token claims). A simple `Set<string>` membership check is sufficient.

**NFR-3: Observability.**
- Log (via pino) when a tool call is rejected due to persona restrictions, including the persona ID, tool name, and task ID.
- Log at session start which tools were exposed to the agent, at `info` level.

**NFR-4: Security.**
- Tool filtering must be enforced server-side. The agent cannot bypass it by manipulating the MCP client.
- The `allowed_mcp_tools` list is an allowlist -- only explicitly listed tools are accessible (deny-by-default).
- Full-access clients (API key auth) are exempt from filtering. This distinction is determined by the token type, not by client-supplied data.

**NFR-5: Testability.**
The tool filtering logic must be a pure function that takes a list of all tool definitions and a set of allowed tool names, and returns the filtered list. This enables unit testing without MCP server infrastructure.

### Integration Points

**With #421 (Core MCP server):** The MCP server must expose a hook or middleware interface where this issue's filtering logic plugs in. The `tools/list` and `tools/call` handlers must support a pre-dispatch filter function.

**With #422 (Full tool surface):** The tool names used in `allowed_mcp_tools` must match the names defined in #422's tool registry. The predefined tool set constants (FR-4) must be updated if tool names change.

**With #423 (Auth & scoped tokens):** The scoped token's JWT claims must include `personaId` (string). The filtering middleware reads this claim to look up the persona's allowed tools. If the token has no `personaId` claim (full-access API key), filtering is skipped.

**With `packages/server/src/grpc-service.ts`:** The `startTask()` and `spawnAgent()` handlers must be updated to pass the MCP server URL and scoped token to the PowerLine `SpawnRequest`, instead of the current `personaMcpServersToJson()` approach for the Grackle MCP server entry.

**With `packages/powerline/src/runtimes/runtime-utils.ts`:** The `resolveMcpServers()` function must be updated to handle the transition from the local MCP stub script to a remote MCP server URL. The auto-injection block (lines 256-262) that adds the `GRACKLE_MCP_SCRIPT` entry is replaced with an entry for the Grackle MCP HTTP endpoint.

**With `packages/powerline/src/runtimes/claude-code.ts`:** The event-stream interception for `post_finding` and `create_subtask` (lines 50-63) must be evaluated for removal once the MCP server handles these tools directly. See FR-10.

**With `packages/common/src/proto/grackle/grackle.proto`:** Proto schema changes for the `Persona` message (FR-6).

**With `packages/server/src/persona-store.ts` and `packages/server/src/schema.ts`:** Database schema and store changes (FR-6).

### Acceptance Criteria -- Unit Tests

**UT-1: Tool filtering pure function.**
Given a full tool list of 35 tools and an allowed set of `["finding_post", "finding_query", "task_create_subtask"]`, the filter function returns exactly those 3 tools.

**UT-2: Empty allowed set returns default worker tools.**
Given an empty `allowed_mcp_tools` array, the filter function returns the 3 default worker tools (`WORKER_TOOLS`).

**UT-3: Unknown tool names in allowed list are ignored.**
Given `allowed_mcp_tools = ["finding_post", "nonexistent_tool"]`, the filter returns only `finding_post`. No error is thrown for the unknown name.

**UT-4: ADMIN_TOOLS bypasses filtering.**
When the allowed set equals `ADMIN_TOOLS` (or a sentinel value like `["*"]`), the filter returns the complete tool list unmodified.

**UT-5: Tool call rejection.**
When a tool call for `env_add` is dispatched but the persona's allowed set is `WORKER_TOOLS`, the middleware returns an MCP error with the expected message format.

**UT-6: Full-access tokens skip filtering.**
When the token type indicates full-access (no `personaId` claim), the middleware passes through all tool calls without filtering.

**UT-7: Persona proto serialization round-trip.**
A `Persona` message with `allowed_mcp_tools = ["finding_post", "task_create_subtask"]` survives proto serialization and deserialization with the field intact.

**UT-8: Persona store persistence.**
Creating a persona with `allowedMcpTools = '["finding_post"]'` and reading it back returns the same value.

**UT-9: Predefined tool set constants.**
`WORKER_TOOLS`, `ORCHESTRATOR_TOOLS`, and `ADMIN_TOOLS` are exported from `@grackle-ai/common` and contain the expected tool names.

### Acceptance Criteria -- Integration Tests

**IT-1: End-to-end tool filtering via MCP protocol.**
Create a persona with `allowed_mcp_tools = ["finding_post"]`. Start a task with that persona. Connect to the MCP server with the task's scoped token. Call `tools/list` and verify only `finding_post` is returned.

**IT-2: Tool call rejection via MCP protocol.**
Using the same scoped token as IT-1, call `tools/call` for `env_list`. Verify the response is an MCP error with the expected message.

**IT-3: Full-access client sees all tools.**
Connect to the MCP server with an API key. Call `tools/list` and verify all ~35 tools are returned.

**IT-4: Default tool set for legacy persona.**
Create a persona without specifying `allowed_mcp_tools`. Start a task with that persona. Verify `tools/list` returns exactly the 3 worker tools.

**IT-5: Persona update reflects in next session.**
Create a persona with worker tools. Start a task (sees 3 tools). Update the persona to add `task_list`. Start a new task with the same persona. Verify the new task sees 4 tools. (The first task's tools do not change mid-session.)

### Acceptance Criteria -- Manual Testing

**MT-1: CLI persona creation with MCP tools.**
Run `grackle persona create "Test Worker" --prompt "You are a worker." --mcp-tools finding_post,finding_query,task_create_subtask`. Run `grackle persona show <id>` and verify the MCP tools are displayed.

**MT-2: CLI preset tool sets.**
Run `grackle persona edit <id> --mcp-tools-preset orchestrator`. Verify the persona's allowed MCP tools match `ORCHESTRATOR_TOOLS`.

**MT-3: Running task with scoped tools.**
Start a task with a worker persona. Observe (via server logs) that the MCP server exposed only 3 tools. If the agent attempts to call a non-permitted tool, verify the rejection is logged.

### Out of Scope

- **MCP server core infrastructure** (port, transport, lifecycle) -- covered by #421.
- **Individual MCP tool implementations** (the ~35 tool handlers) -- covered by #422.
- **Authentication middleware and token issuance** -- covered by #423. This issue consumes the `personaId` claim from the token but does not implement token generation or validation.
- **Per-tool parameter scoping** (e.g., restricting `task_list` to only the task's own project) -- this is a finer-grained authorization concern that can be addressed in a follow-up.
- **Web UI for managing persona MCP tools** -- the web UI may add tool configuration later; this issue covers only the proto/server/CLI layers.
- **Runtime-specific tool filtering** (e.g., `ToolConfig.allowed_tools` for Claude Agent SDK built-in tools like `Bash`, `Write`) -- this already works independently and is not changed by this issue.
- **Dynamic tool injection** (adding tools at runtime that are not in the static registry) -- not in scope.

### Open Questions

**OQ-1: Tool naming finality.**
The `allowed_mcp_tools` values depend on the tool names defined in #422, which is not yet implemented. Should this issue block on #422's tool naming, or should we define the filtering infrastructure with placeholder names and update once #422 lands? **Recommendation**: Implement the infrastructure now with the predefined constants using provisional names. Update the constants when #422 finalizes tool names.

**OQ-2: Wildcard patterns in `allowed_mcp_tools`.**
Should we support glob patterns like `task_*` to allow all tools in a group, or require explicit enumeration? Wildcards are more convenient but harder to audit. **Recommendation**: Support both exact names and `group_*` prefix patterns. The predefined constants (`ORCHESTRATOR_TOOLS`) can use exact names internally, but custom personas can use wildcards for convenience.

**OQ-3: Per-MCP-server scoping vs global tool names.**
The current `resolveMcpServers()` uses `mcp__<serverName>__<toolName>` namespacing for `disallowedTools`. Should `allowed_mcp_tools` use the same `mcp__grackle__<toolName>` format, or just plain tool names since it only applies to the Grackle MCP server? **Recommendation**: Use plain tool names (e.g., `finding_post` not `mcp__grackle__finding_post`) since this field specifically controls the Grackle MCP server's tool surface. The `mcp__` prefix is an agent SDK convention, not an MCP protocol concept.

**OQ-4: Event-stream interception removal timing.**
Should the removal of event-stream interception for `post_finding`/`create_subtask` in `claude-code.ts` (FR-10) happen in this issue, or in a follow-up? Removing it requires the MCP server's tool handlers (#422) to be fully functional. **Recommendation**: Keep the interception code during this issue's implementation with a `// TODO(#424): Remove once MCP server handles these tools directly` comment. Remove in a follow-up after #422 is merged and verified.

**OQ-5: Immutable vs mutable tool set during a session.**
If a persona's `allowed_mcp_tools` is updated while a task is running, should the running session see the new tools? **Recommendation**: No. The tool set is resolved at session start and cached for the session's lifetime. This matches the current behavior where MCP config is baked into the spawn request. A new task must be started to pick up tool changes.
